# Generated by Django 3.2.8 on 2021-10-20 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('pool1_name', models.CharField(max_length=100)),
                ('pool1_count', models.FloatField(default=0)),
                ('pool1_percent', models.FloatField(default=0)),
                ('pool2_name', models.CharField(max_length=100)),
                ('pool2_count', models.FloatField(default=0)),
                ('pool2_percent', models.FloatField(default=0)),
                ('pool3_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pool3_count', models.FloatField(default=0)),
                ('pool3_percent', models.FloatField(default=0)),
                ('pool4_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pool4_count', models.FloatField(default=0)),
                ('pool4_percent', models.FloatField(default=0)),
                ('pool_over_time', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoolData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolapp.pool')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
