# Generated by Django 3.2.8 on 2021-10-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='pool_over_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
