# Generated by Django 3.2.8 on 2021-10-22 08:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0002_alter_pool_pool_over_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='Image',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
