# Generated by Django 3.2.8 on 2021-10-22 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolapp', '0003_pool_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pool',
            old_name='Image',
            new_name='image',
        ),
    ]
